apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: minikubes.alexellis.io
spec:
  group: alexellis.io
  names:
    kind: Minikube
    listKind: MinikubeList
    plural: minikubes
    singular: minikube
  scope: Namespaced
  version: v1alpha1
