apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    name: squid-proxy
    namespace: clusters
  spec:
    selector:
      matchLabels:
        daemonset: squid-proxy
    template:
      metadata:
        creationTimestamp: null
        labels:
          daemonset: squid-proxy
      spec:
        containers:
        - image: alexellis2/squid-proxy:0.2
          imagePullPolicy: IfNotPresent
          name: proxy
          ports:
          - containerPort: 3129
            hostPort: 3129
            name: squid
            protocol: TCP
          resources: {}
        dnsPolicy: ClusterFirst
        hostNetwork: true
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 1
      type: RollingUpdate
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
