kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: minikube
  namespace: clusters
rules:
- apiGroups:
  - alexellis.io
  - extensions
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - daemonsets
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-minikube
  namespace: clusters
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: minikube
  apiGroup: rbac.authorization.k8s.io
